# Generated by Django 3.2.6 on 2021-12-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('hobby_idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('hobby', models.CharField(max_length=40)),
                ('img_file_name', models.CharField(max_length=40)),
            ],
        ),
    ]
