# Generated by Django 3.2.6 on 2021-12-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardBBS', '0002_auto_20211216_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='image',
            field=models.ImageField(blank=True, upload_to='boardBBS/images'),
        ),
    ]
