# Generated by Django 3.2.6 on 2021-12-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardBBS', '0003_hobby_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='image',
        ),
        migrations.AlterField(
            model_name='hobby',
            name='img_file_name',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
